apiVersion: apps/v1
kind: Deployment
metadata:
  name: color-page
  labels:
    app: color-page
spec:
  replicas: 2
  selector:
    matchLabels:
      app: color-page
  template:
    metadata:
      labels:
        app: color-page
    spec:
      containers:
        - name: color-page
          image: color-page:v1          # Image name built into minikube
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: PAGE_COLOR
              value: "lightgreen"
            - name: PAGE_TEXT
              value: "Color Page running on minikube!"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
