apiVersion: apps/v1
kind: Deployment
metadata:
  name: color-page
  labels:
    app: color-page
spec:
  replicas: 1
  selector:
    matchLabels:
      app: color-page
  template:
    metadata:
      labels:
        app: color-page
    spec:
      containers:
        - name: color-page
          image: chaithu0011/color-app:latest          
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: PAGE_COLOR
              value: "lightgreen"
            - name: PAGE_TEXT
              value: "Color Page running on EKS!"
