apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: color-page
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: chaithanya.com
      http:
        paths:
          - path: /web-app
            pathType: Prefix
            backend:
              service:
                name: color-page
                port:
                  number: 80
