apiVersion: v1
kind: Service
metadata:
  name: color-page
  labels:
    app: color-page
spec:
  selector:
    app: color-page
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: NodePort
